/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TQrTokenRouteImport } from './routes/t.$qrToken'
import { Route as RRestaurantSlugRouteImport } from './routes/r.$restaurantSlug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DashboardTablesRouteImport } from './routes/dashboard.tables'
import { Route as DashboardStaffRouteImport } from './routes/dashboard.staff'
import { Route as DashboardRequestsRouteImport } from './routes/dashboard.requests'
import { Route as DashboardMenuRouteImport } from './routes/dashboard.menu'
import { Route as DashboardKitchenRouteImport } from './routes/dashboard.kitchen'
import { Route as DashboardBranchesRouteImport } from './routes/dashboard.branches'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as RRestaurantSlugBranchSlugRouteImport } from './routes/r.$restaurantSlug.$branchSlug'
import { Route as AdminRestaurantsIdRouteImport } from './routes/admin.restaurants.$id'
import { Route as TQrTokenOrderOrderIdRouteImport } from './routes/t.$qrToken.order.$orderId'
import { Route as RRestaurantSlugBranchSlugWelcomeRouteImport } from './routes/r.$restaurantSlug.$branchSlug.welcome'
import { Route as RRestaurantSlugBranchSlugTablesRouteImport } from './routes/r.$restaurantSlug.$branchSlug.tables'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TQrTokenRoute = TQrTokenRouteImport.update({
  id: '/t/$qrToken',
  path: '/t/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)
const RRestaurantSlugRoute = RRestaurantSlugRouteImport.update({
  id: '/r/$restaurantSlug',
  path: '/r/$restaurantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTablesRoute = DashboardTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKitchenRoute = DashboardKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBranchesRoute = DashboardBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const RRestaurantSlugBranchSlugRoute =
  RRestaurantSlugBranchSlugRouteImport.update({
    id: '/$branchSlug',
    path: '/$branchSlug',
    getParentRoute: () => RRestaurantSlugRoute,
  } as any)
const AdminRestaurantsIdRoute = AdminRestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRestaurantsRoute,
} as any)
const TQrTokenOrderOrderIdRoute = TQrTokenOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => TQrTokenRoute,
} as any)
const RRestaurantSlugBranchSlugWelcomeRoute =
  RRestaurantSlugBranchSlugWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => RRestaurantSlugBranchSlugRoute,
  } as any)
const RRestaurantSlugBranchSlugTablesRoute =
  RRestaurantSlugBranchSlugTablesRouteImport.update({
    id: '/tables',
    path: '/tables',
    getParentRoute: () => RRestaurantSlugBranchSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/restaurants': typeof AdminRestaurantsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/kitchen': typeof DashboardKitchenRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$restaurantSlug': typeof RRestaurantSlugRouteWithChildren
  '/t/$qrToken': typeof TQrTokenRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/restaurants/$id': typeof AdminRestaurantsIdRoute
  '/r/$restaurantSlug/$branchSlug': typeof RRestaurantSlugBranchSlugRouteWithChildren
  '/r/$restaurantSlug/$branchSlug/tables': typeof RRestaurantSlugBranchSlugTablesRoute
  '/r/$restaurantSlug/$branchSlug/welcome': typeof RRestaurantSlugBranchSlugWelcomeRoute
  '/t/$qrToken/order/$orderId': typeof TQrTokenOrderOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/restaurants': typeof AdminRestaurantsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/kitchen': typeof DashboardKitchenRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$restaurantSlug': typeof RRestaurantSlugRouteWithChildren
  '/t/$qrToken': typeof TQrTokenRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/restaurants/$id': typeof AdminRestaurantsIdRoute
  '/r/$restaurantSlug/$branchSlug': typeof RRestaurantSlugBranchSlugRouteWithChildren
  '/r/$restaurantSlug/$branchSlug/tables': typeof RRestaurantSlugBranchSlugTablesRoute
  '/r/$restaurantSlug/$branchSlug/welcome': typeof RRestaurantSlugBranchSlugWelcomeRoute
  '/t/$qrToken/order/$orderId': typeof TQrTokenOrderOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/restaurants': typeof AdminRestaurantsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/kitchen': typeof DashboardKitchenRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/r/$restaurantSlug': typeof RRestaurantSlugRouteWithChildren
  '/t/$qrToken': typeof TQrTokenRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/restaurants/$id': typeof AdminRestaurantsIdRoute
  '/r/$restaurantSlug/$branchSlug': typeof RRestaurantSlugBranchSlugRouteWithChildren
  '/r/$restaurantSlug/$branchSlug/tables': typeof RRestaurantSlugBranchSlugTablesRoute
  '/r/$restaurantSlug/$branchSlug/welcome': typeof RRestaurantSlugBranchSlugWelcomeRoute
  '/t/$qrToken/order/$orderId': typeof TQrTokenOrderOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/admin/analytics'
    | '/admin/branches'
    | '/admin/login'
    | '/admin/restaurants'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard/branches'
    | '/dashboard/kitchen'
    | '/dashboard/menu'
    | '/dashboard/requests'
    | '/dashboard/staff'
    | '/dashboard/tables'
    | '/invite/$token'
    | '/r/$restaurantSlug'
    | '/t/$qrToken'
    | '/admin/'
    | '/dashboard/'
    | '/admin/restaurants/$id'
    | '/r/$restaurantSlug/$branchSlug'
    | '/r/$restaurantSlug/$branchSlug/tables'
    | '/r/$restaurantSlug/$branchSlug/welcome'
    | '/t/$qrToken/order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin/analytics'
    | '/admin/branches'
    | '/admin/login'
    | '/admin/restaurants'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard/branches'
    | '/dashboard/kitchen'
    | '/dashboard/menu'
    | '/dashboard/requests'
    | '/dashboard/staff'
    | '/dashboard/tables'
    | '/invite/$token'
    | '/r/$restaurantSlug'
    | '/t/$qrToken'
    | '/admin'
    | '/dashboard'
    | '/admin/restaurants/$id'
    | '/r/$restaurantSlug/$branchSlug'
    | '/r/$restaurantSlug/$branchSlug/tables'
    | '/r/$restaurantSlug/$branchSlug/welcome'
    | '/t/$qrToken/order/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/admin/analytics'
    | '/admin/branches'
    | '/admin/login'
    | '/admin/restaurants'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard/branches'
    | '/dashboard/kitchen'
    | '/dashboard/menu'
    | '/dashboard/requests'
    | '/dashboard/staff'
    | '/dashboard/tables'
    | '/invite/$token'
    | '/r/$restaurantSlug'
    | '/t/$qrToken'
    | '/admin/'
    | '/dashboard/'
    | '/admin/restaurants/$id'
    | '/r/$restaurantSlug/$branchSlug'
    | '/r/$restaurantSlug/$branchSlug/tables'
    | '/r/$restaurantSlug/$branchSlug/welcome'
    | '/t/$qrToken/order/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RRestaurantSlugRoute: typeof RRestaurantSlugRouteWithChildren
  TQrTokenRoute: typeof TQrTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/t/$qrToken': {
      id: '/t/$qrToken'
      path: '/t/$qrToken'
      fullPath: '/t/$qrToken'
      preLoaderRoute: typeof TQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$restaurantSlug': {
      id: '/r/$restaurantSlug'
      path: '/r/$restaurantSlug'
      fullPath: '/r/$restaurantSlug'
      preLoaderRoute: typeof RRestaurantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tables': {
      id: '/dashboard/tables'
      path: '/tables'
      fullPath: '/dashboard/tables'
      preLoaderRoute: typeof DashboardTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/requests': {
      id: '/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kitchen': {
      id: '/dashboard/kitchen'
      path: '/kitchen'
      fullPath: '/dashboard/kitchen'
      preLoaderRoute: typeof DashboardKitchenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/branches': {
      id: '/dashboard/branches'
      path: '/branches'
      fullPath: '/dashboard/branches'
      preLoaderRoute: typeof DashboardBranchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/r/$restaurantSlug/$branchSlug': {
      id: '/r/$restaurantSlug/$branchSlug'
      path: '/$branchSlug'
      fullPath: '/r/$restaurantSlug/$branchSlug'
      preLoaderRoute: typeof RRestaurantSlugBranchSlugRouteImport
      parentRoute: typeof RRestaurantSlugRoute
    }
    '/admin/restaurants/$id': {
      id: '/admin/restaurants/$id'
      path: '/$id'
      fullPath: '/admin/restaurants/$id'
      preLoaderRoute: typeof AdminRestaurantsIdRouteImport
      parentRoute: typeof AdminRestaurantsRoute
    }
    '/t/$qrToken/order/$orderId': {
      id: '/t/$qrToken/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/t/$qrToken/order/$orderId'
      preLoaderRoute: typeof TQrTokenOrderOrderIdRouteImport
      parentRoute: typeof TQrTokenRoute
    }
    '/r/$restaurantSlug/$branchSlug/welcome': {
      id: '/r/$restaurantSlug/$branchSlug/welcome'
      path: '/welcome'
      fullPath: '/r/$restaurantSlug/$branchSlug/welcome'
      preLoaderRoute: typeof RRestaurantSlugBranchSlugWelcomeRouteImport
      parentRoute: typeof RRestaurantSlugBranchSlugRoute
    }
    '/r/$restaurantSlug/$branchSlug/tables': {
      id: '/r/$restaurantSlug/$branchSlug/tables'
      path: '/tables'
      fullPath: '/r/$restaurantSlug/$branchSlug/tables'
      preLoaderRoute: typeof RRestaurantSlugBranchSlugTablesRouteImport
      parentRoute: typeof RRestaurantSlugBranchSlugRoute
    }
  }
}

interface AdminRestaurantsRouteChildren {
  AdminRestaurantsIdRoute: typeof AdminRestaurantsIdRoute
}

const AdminRestaurantsRouteChildren: AdminRestaurantsRouteChildren = {
  AdminRestaurantsIdRoute: AdminRestaurantsIdRoute,
}

const AdminRestaurantsRouteWithChildren =
  AdminRestaurantsRoute._addFileChildren(AdminRestaurantsRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRestaurantsRoute: AdminRestaurantsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBranchesRoute: typeof DashboardBranchesRoute
  DashboardKitchenRoute: typeof DashboardKitchenRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardTablesRoute: typeof DashboardTablesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBranchesRoute: DashboardBranchesRoute,
  DashboardKitchenRoute: DashboardKitchenRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardTablesRoute: DashboardTablesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface RRestaurantSlugBranchSlugRouteChildren {
  RRestaurantSlugBranchSlugTablesRoute: typeof RRestaurantSlugBranchSlugTablesRoute
  RRestaurantSlugBranchSlugWelcomeRoute: typeof RRestaurantSlugBranchSlugWelcomeRoute
}

const RRestaurantSlugBranchSlugRouteChildren: RRestaurantSlugBranchSlugRouteChildren =
  {
    RRestaurantSlugBranchSlugTablesRoute: RRestaurantSlugBranchSlugTablesRoute,
    RRestaurantSlugBranchSlugWelcomeRoute:
      RRestaurantSlugBranchSlugWelcomeRoute,
  }

const RRestaurantSlugBranchSlugRouteWithChildren =
  RRestaurantSlugBranchSlugRoute._addFileChildren(
    RRestaurantSlugBranchSlugRouteChildren,
  )

interface RRestaurantSlugRouteChildren {
  RRestaurantSlugBranchSlugRoute: typeof RRestaurantSlugBranchSlugRouteWithChildren
}

const RRestaurantSlugRouteChildren: RRestaurantSlugRouteChildren = {
  RRestaurantSlugBranchSlugRoute: RRestaurantSlugBranchSlugRouteWithChildren,
}

const RRestaurantSlugRouteWithChildren = RRestaurantSlugRoute._addFileChildren(
  RRestaurantSlugRouteChildren,
)

interface TQrTokenRouteChildren {
  TQrTokenOrderOrderIdRoute: typeof TQrTokenOrderOrderIdRoute
}

const TQrTokenRouteChildren: TQrTokenRouteChildren = {
  TQrTokenOrderOrderIdRoute: TQrTokenOrderOrderIdRoute,
}

const TQrTokenRouteWithChildren = TQrTokenRoute._addFileChildren(
  TQrTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  InviteTokenRoute: InviteTokenRoute,
  RRestaurantSlugRoute: RRestaurantSlugRouteWithChildren,
  TQrTokenRoute: TQrTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
